# Site settings
title: Kang Blog
SEOTitle: 刘康的博客 | Kang Blog
header-img: img/post-bg-desk.jpg
email: 18337026860@163.com
description: "Every failure is leading towards success!"
keyword: "Kang, Kang Blog, 刘康的博客, luckykang, 刘康, WepApp Vue React Wexx"
url: "http://luckykang.cn"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lucky-kang/lucky-kang.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "目标决定你将成为什么样的人！"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:   LiuKang111
zhihu_username:     lucky-kang-life
github_username:    lucky-kang
jianshu_username:   luckykang




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: luckykang

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 20b2373051fb1bd2f5cc                            #生成的clientID
  clientSecret: a334dc93589476e7e5ed7f3b08757e7866316888    #生成的clientSecret
  repo: lucky-kang.github.io    #仓库名称
  owner: lucky-kang    #github用户名
  admin: 刘康
  distractionFreeMode: false #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: ecec2a05ce3f297ef603c8279a578425

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: luckykang.cn               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#FF6347"
service-worker: true



# Friends
friends: [
    {
        title: "听风来の博客",
        href: "http://kanglucky.cn"
    },{
        title: "Vue",
        href: "https://cn.vuejs.org/"
    },{
        title: "React",
        href: "http://react.css88.com/"
    }
]
